name: Publish to Marketplace
on:
  push:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Increment VSIX Version
        id: vsix_version
        uses: timheuer/vsix-version-stamp@v2
        with:
          manifest-file: './source.extension.vsixmanifest'

      - name: Restore NuGet Packages
        run: dotnet restore MatrixUltrA12.slnx -p:RuntimeIdentifier=win

      - name: Build VSIX  
        run: msbuild MatrixUltrA12.slnx /p:Configuration=Release /p:RuntimeIdentifier=win /p:DeployExtension=false /p:ZipPackageCompressionLevel=Normal


      - name: Publish to Marketplace
        uses: CodingWithCalvin/GHA-VSMarketplacePublisher@v2.0.0
        with:
          marketplace-pat: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
          vsix-path: './bin/Release/MatrixUltrA12.vsix'
          publish-manifest-path: 'publish-manifest.json'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.vsix_version.outputs.version }}
          name: Release v${{ steps.vsix_version.outputs.version }}
          files: 'MatrixUltrA12/bin/Release/MatrixUltrA12.vsix'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
